### ISSUE TITLE
Delete all messages should ask for confirm

### ISSUE THREAD

**Issue by amigthea** [seird/gotify-tray-cpp#4]
as per title, the button position, near the window button, can easily be misclicked so I think a warning message could be helpful

**Comment by seird** [comment]
The "delete all messages" button deletes all the messages in the currently selected application in the list on the left and it should show a message like this if there are messages that will be deleted:
![image](https://github.com/user-attachments/assets/049e68fe-0c95-4c60-8a25-3b1d3689b4fb)

If you click the button when an application is selected that doesn't have any messages, it won't do anything at all. Are any of your messages getting deleted when you press that button and you don't get a warning?

**Comment by amigthea** [comment]
If the warning already exist then it's me who misremembers the course of actions that led me to lose all stored messages. Could an "undo" action be implemented, like the android app, for extra safety? thanks for your work anyway, I'm using this every day and it's awesome

**Comment by seird** [comment]
I don't think the complexity is worth the limited usefulness this feature would add.
The buttons could be in a better location, but considering the warning that is in place, no harm can be done by accidentally clicking the button.
