### ISSUE TITLE
[Feature] Support for html URLs

### ISSUE THREAD

**Issue by amigthea** [seird/gotify-tray-cpp#5]
can html syntax be supported like in android version?

for example, [changedetection](https://github.com/dgtlmoon/changedetection.io) can include URLs but those are displayed as `<a href="https://mylink.com/link">https://mylink.com/link</a>` instead of a clickable link

**Comment by seird** [comment]
It's supposed to make urls clickable, but that's a bug -- should be fixed in the `fix-html-urls` branch but haven't tested properly yet

**Comment by seird** [comment]
Should be fixed now.. hopefully not breaking anything else
PKGBUILD: https://gist.github.com/seird/c7520f2ddc5ce1a46884d35bd15982fd#file-pkgbuild

**Comment by amigthea** [comment]
I'm facing a strange behaviour, I'm receiving this string in the message body

`[shodan](https://shodan.io/host/89.46.xxx.xxx)`

and some times ago it stopped working on gotify-tray-cpp:
if advanced option "Force plain text in the message widget" is not enabled, the link is not displayed at all

![Image](https://github.com/user-attachments/assets/2ceae7ae-d176-4abb-83ce-ea050154ce73)

if that option is enabled I can see the string but is not a link

**Comment by seird** [comment]
It not being rendered at all happens because the message has the display field set to `text/markdown` and qt doesn't handle it properly I guess. I think I'll just remove the markdown formatting completely

**Comment by amigthea** [comment]
I can confirm that is a markdown call

`"contentType": "text/markdown"`

maybe the formatting could be set as a toggle option?
